config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show'
  end
  resources :users, only: [:show]
  resources :books
  root 'books#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # ロケール振り分けを全てのアクションで実行
  around_action :switch_locale

  # DeviseのStrongParameterを受け付ける
  before_action :configure_permitted_parameters, if: :devise_controller?

  # paramsのロケールによる振り分け
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  # url_for関係メソッドでロケールを設定するよう上書き
  def default_url_options
    { locale: I18n.locale }
  end

  protected

  # Devise StrongParameterに独自属性を追加
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name zip_code address biography])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name zip_code address biography])
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page(params[:page]).per(10)
  end

  # GET /books/1
  # GET /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(@book, notice: t('.success'))
    else
      render(:new)
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      redirect_to(@book, notice: t('.success'))
    else
      render(:edit)
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    redirect_to books_url, notice: t('.success')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :memo, :author, :picture)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_for_github_oauth(request.env['omniauth.auth'], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Gitub') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # GET /resource
  def show
    @user = User.find(params[:id])
    render 'devise/registrations/show'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = t('activerecord.errors.template.header', count: @book.errors.count)
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :memo
    = f.text_area :memo
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :picture
    = f.file_field :picture
  .actions
    = f.submit t('nav.save')

app/views/books/edit.html.haml
%h1
  = t('.page_title')

= render 'form'

= link_to t('nav.show'), @book
\|
= link_to t('nav.back'), books_path

app/views/books/index.html.haml
%h1
  = t('.page_title')

%table
  %thead
    %tr
      %th= Book.human_attribute_name(:title)
      %th= Book.human_attribute_name(:memo)
      %th= Book.human_attribute_name(:author)
      %th= Book.human_attribute_name(:picture)
      %th
      %th
      %th

  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.memo
        %td= book.author
        %td= book.picture
        %td= link_to t('nav.show'), book
        %td= link_to t('nav.edit'), edit_book_path(book)
        %td
          = link_to(t('nav.destroy'),
                    book,
                    method: :delete,
                    data: { confirm: t('nav.destroy_confirm') })

%br

= paginate @books

= link_to t('nav.new'), new_book_path

app/views/books/new.html.haml
%h1
  = t('.page_title')

= render 'form'

= link_to t('nav.back'), books_path

app/views/books/show.html.haml
%p
  %b= "#{Book.human_attribute_name(:title)}:"
  = @book.title
%p
  %b= "#{Book.human_attribute_name(:memo)}:"
  = @book.memo
%p
  %b= "#{Book.human_attribute_name(:author)}:"
  = @book.author
%p
  %b= "#{Book.human_attribute_name(:picture)}:"
  = image_tag @book.picture_url if @book.picture.present?

= link_to t('nav.edit'), edit_book_path(@book)
\|
= link_to t('nav.back'), books_path

app/views/layouts/_header.html.haml
- i18n_devise_scope = 'devise.shared.links'
%nav
  = link_to(root_path, id: "logo") do
    %h1
      = t('app_title')

  - if user_signed_in?
    = link_to(user_path(current_user.id),
              id: "user-registration-link") do
      = current_user.name
  - else
    = link_to(new_user_session_path,
              id: 'sign-in-link') do
      = t('sign_in', scope: i18n_devise_scope)
    = link_to(new_user_registration_path,
              id: 'sign-in-link') do
      = t('sign_up', scope: i18n_devise_scope)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = t('app_title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header'
    - unless flash.empty?
      .container
        - flash.each do |message_type, message|
          = content_tag(:div, message, class: "alert alert-#{message_type}")

    = yield

    - if Rails.env.development?
      .card
        = debug(params)